# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0016_auto_20160707_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbsubmissionprotein',
            name='protein_id',
            field=models.ForeignKey(blank=True, db_column='protein_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbProtein'),
#            field=models.ForeignKey(blank=True, db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbProtein'),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionprotein',
            name='submission_id',
            field=models.ForeignKey(blank=True, db_column='submission_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
        ),
    ]
