# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0017_auto_20160714_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbfiles',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='dyndbdynamics',
            name='submission_id',
            field=models.ForeignKey(blank=True, db_column='submission_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
        ),
        migrations.AlterField(
            model_name='dyndbexpinteractiondata',
            name='ligand1',
            field=models.ForeignKey(blank=True, db_column='ligand1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbExpInteractionData_ligand1_fky', to='dynadb.DyndbCompound'),
        ),
        migrations.AlterField(
            model_name='dyndbexpinteractiondata',
            name='ligand2',
            field=models.ForeignKey(blank=True, db_column='ligand2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbExpInteractionData_ligand2_fky', to='dynadb.DyndbCompound'),
        ),
        migrations.AlterField(
            model_name='dyndbexpproteindata',
            name='id_protein',
            field=models.ForeignKey(db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbProtein'),
        ),
        migrations.AlterField(
            model_name='dyndbfilesdynamics',
            name='id_dynamics',
            field=models.ForeignKey(db_column='id_dynamics', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbDynamics'),
        ),
        migrations.AlterField(
            model_name='dyndbfilesdynamics',
            name='id_files',
            field=models.ForeignKey(db_column='id_files', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbFiles'),
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='id_complex_molecule',
            field=models.ForeignKey(blank=True, db_column='id_complex_molecule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbComplexMolecule'),
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='id_protein',
            field=models.ForeignKey(blank=True, db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbProtein'),
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='id_structure_model',
            field=models.ForeignKey(blank=True, db_column='id_structure_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.StructureModel'),
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='template_id_model',
            field=models.ForeignKey(blank=True, db_column='template_id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbModel'),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='id_model',
            field=models.ForeignKey(db_column='id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_id_model_fky', to='dynadb.DyndbModel'),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='template_id_model',
            field=models.ForeignKey(blank=True, db_column='template_id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_template_id_protein_fky', to='dynadb.DyndbModel'),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmodel',
            name='model_id',
            field=models.ForeignKey(blank=True, db_column='model_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbModel'),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmodel',
            name='submission_id',
            field=models.ForeignKey(blank=True, db_column='submission_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmolecule',
            name='molecule_id',
            #field=models.ForeignKey(blank=True, db_column='id_molecule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbMolecule'),
            field=models.ForeignKey(blank=True, db_column='molecule_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbMolecule'),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmolecule',
            name='submission_id',
#            field=models.ForeignKey(blank=True, db_column='id_submission', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
            field=models.ForeignKey(blank=True, db_column='submission_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
        ),
    ]
