# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0018_auto_20160714_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbproteinmutations',
            options={'managed': True},
        ),
    ]
