# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0022_auto_20160719_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbprotein',
            options={'managed': False},
        ),
    ]
