# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0024_auto_20160726_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyndbUniprotSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5, null=True)),
                ('kingdom', models.CharField(max_length=1)),
                ('taxon_node', models.IntegerField(null=True)),
                ('scientific_name', models.TextField(db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'dyndb_uniprot_species',
            },
        ),
        migrations.CreateModel(
            name='DyndbUniprotSpeciesAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=200)),
                ('name_type', models.CharField(choices=[('C', 'Common name'), ('S', 'Synonym')], max_length=1)),
                ('id_uniprot_species', models.ForeignKey(db_column='id_uniprot_species', on_delete=django.db.models.deletion.CASCADE, to='dynadb.DyndbUniprotSpecies')),
            ],
            options={
                'db_table': 'dyndb_uniprot_species_aliases',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dyndbuniprotspeciesaliases',
            unique_together=set([('name', 'id_uniprot_species')]),
        ),
    ]
