# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0025_auto_20160920_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcomplexprotein',
            name='id_complex_exp',
            field=models.ForeignKey(db_column='id_complex_exp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbComplexExp'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexprotein',
            name='id_protein',
            field=models.ForeignKey(db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbProtein'),
        ),
    ]
