# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0028_auto_20160911_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbmodeledresidues',
            name='bound_to_id_modeled_residues',
            field=models.ForeignKey(db_column='bound_to_id_modeled_residues', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_bound_to_id_modeled_residues_fky', to='dynadb.DyndbModeledResidues'),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, 'X-ray'), (1, 'NMR'), (2, 'Ab-initio'), (3, 'Homology'), (4, 'Threading'), (5, 'MD'), (6, 'Other Computational Methods')], default=0),
        ),
    ]
