# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0029_auto_20160911_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcomplexmoleculemolecule',
            options={'managed': True},
        ),
    ]
