# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0031_auto_20160911_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbfiletypes',
            options={'managed': True},
        ),
    ]
