# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0034_auto_20160912_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbfilesmolecule',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Molecule'), (1, 'Image 100px'), (2, 'Image 300px')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbfilesdynamics',
            unique_together=set([('id_dynamics', 'id_files')]),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbfilesmolecule',
            unique_together=set([('id_molecule', 'id_files', 'type')]),
        ),
    ]
