# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0035_auto_20160912_0039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dyndbfilesdynamics',
            unique_together=set([('id_dynamics', 'id_files', 'type')]),
        ),
    ]
