# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0036_auto_20160912_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbfilesdynamics',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Input coordinates'), (1, 'Input topology'), (2, 'Trajectory'), (3, 'Parameters'), (4, 'Others')], default=0),
        ),
    ]
