# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0038_auto_20160919_1803'),
        ('dynadb', '0026_auto_20160920_1125'),
    ]

    operations = [
    ]
