# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0040_auto_20160921_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbprotein',
            name='receptor_id_protein',
            field=models.ForeignKey(blank=True, db_column='receptor_id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.Protein'),
        ),
    ]
