# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0041_auto_20160930_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcompound',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dyndbmolecule',
            options={'managed': True},
        ),
    ]
