# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-17 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0046_dyndbsubmissionmolecule_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcomplexmolecule',
            options={'managed': True},
        ),
    ]
