# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0048_auto_20161017_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbcomplexmoleculemolecule',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Orthosteric ligand'), (1, 'Allosteric ligand'), (2, 'Crystallographic waters'), (3, 'Other')], default=0),
        ),
    ]
