# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0049_dyndbcomplexmoleculemolecule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyndbcomplexmolecule',
            name='type',
        ),
    ]
