# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0050_remove_dyndbcomplexmolecule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='bonded_to_id_modeled_residues',
            field=models.ForeignKey(blank=True, db_column='bond_to_id_modeled_residues', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_bond_to_id_modeled_residues_fky', to='dynadb.DyndbModeledResidues'),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='template_id_model',
            field=models.ForeignKey(blank=True, db_column='template_id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_template_id_protein_fky', to='dynadb.DyndbModel'),
        ),
        migrations.AlterField(
            model_name='dyndbprotein',
            name='name',
            field=models.TextField(),
        ),
    ]
