# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0051_auto_20161019_1805'),
        ('dynadb', '0041_auto_20161007_2001'),
    ]

    operations = [
    ]
