# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0056_auto_20161106_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbsubmissionmolecule',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Orthosteric ligand'), (1, 'Allosteric ligand'), (2, 'Crystallographic waters, lipids or ions'), (3, 'Other')], default=0),
        ),
    ]
