# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0042_auto_20161026_1718'),
        ('dynadb', '0057_auto_20161116_2004'),
    ]

    operations = [
    ]
