# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0058_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcomplexcompound',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
