# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0058_auto_20161124_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbfiles',
            options={'managed': True},
        ),
    ]
