# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0059_auto_20161129_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbfiles',
            name='url',
            field=models.CharField(blank=True, max_length=520, null=True),
        ),
    ]
