# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-07 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0060_auto_20161121_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dyndbfilesmolecule',
            unique_together=set([('id_molecule', 'id_files', 'type'), ('id_molecule', 'id_files')]),
        ),
    ]
