# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0062_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbmodel',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Apoform'), (1, 'Complex')], default=0),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmolecule',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Orthosteric ligand'), (1, 'Allosteric ligand'), (2, 'Crystallographic waters'), (3, 'Crystallographic lipids'), (4, 'Crystallographic ions'), (5, 'Other')], default=0, null=True),
        ),
    ]
