# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0065_auto_20161222_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbdynamicscomponents',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Ions'), (1, 'Ligand'), (2, 'Lipid'), (3, 'Water'), (4, 'Other')], default=0),
        ),
    ]
