# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('dynadb', '0069_auto_20170109_1602'), ('dynadb', '0070_dyndbsubmissiondynamicsfiles_framenum'), ('dynadb', '0071_auto_20170109_1919'), ('dynadb', '0072_auto_20170109_1931')]

    dependencies = [
        ('dynadb', '0068_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyndbSubmissionDynamicsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Input coordinates'), (1, 'Input topology'), (2, 'Trajectory'), (3, 'Parameters'), (4, 'Others')], default=0)),
                ('filename', models.CharField(max_length=80, unique=True)),
                ('filepath', models.CharField(max_length=520)),
                ('url', models.CharField(max_length=520, null=True)),
                ('submission_id', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission')),
                ('framenum', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'dyndb_submission_dynamics_files',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='dyndbsubmissiondynamicsfiles',
            unique_together=set([('submission_id', 'filepath')]),
        ),
    ]
