# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0069_auto_20170109_1756'),
        ('dynadb', '0069_auto_20170109_1602_squashed_0072_auto_20170109_1931'),
    ]

    operations = [
    ]
