# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0069_auto_20170107_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbcomplexexp',
            name='ec_fifty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dyndbcomplexexp',
            name='ic_fifty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dyndbcomplexexp',
            name='kd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dyndbcomplexexp',
            name='ki',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
