# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0070_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='id_protein',
            field=models.ForeignKey(db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbProtein'),
        ),
    ]
