# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0072_auto_20170118_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbbinding',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dyndbefficacy',
            options={'managed': True},
        ),
    ]
