# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0073_auto_20170119_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbreferences',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital object identifier.', max_length=80, null=True, unique=True, verbose_name='DOI'),
        ),
    ]
