# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0073_auto_20170123_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbbinding',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='dyndbefficacy',
            name='description',
            field=models.CharField(max_length=900),
        ),
    ]
