# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0073_auto_20170120_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbmodelcomponents',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Ions'), (1, 'Ligand'), (2, 'Lipid'), (3, 'Water'), (4, 'Other')], default=0, null=True),
        ),
    ]
