# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0073_auto_20170120_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dyndbsubmission',
            unique_together=set([('id', 'user_id')]),
        ),
    ]
