# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0074_auto_20170124_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbreferences',
            name='url',
            field=models.URLField(blank=True, help_text='Uniform Resource Locator to the publication resource', max_length=100, null=True, verbose_name='URL'),
        ),
    ]
