# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0074_auto_20170125_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbsubmission',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
