# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0075_auto_20170125_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbsubmission',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dyndbsubmission',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
