# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0076_auto_20170126_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='pdbid',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
