# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0077_auto_20170207_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dyndbcompound',
            old_name='chembleid',
            new_name='chemblid',
        ),
    ]
