# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0077_dyndbsubmission_is_reuse_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbsubmission',
            name='is_ready_for_publication',
            field=models.BooleanField(default=False),
        ),
    ]
