# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-02 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0078_dyndbsubmission_is_ready_for_publication'),
        ('dynadb', '0076_auto_20170126_1834'),
    ]

    operations = [
    ]
