# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 18:18
# Generated by Django 1.9.2 on 2017-02-14 18:20
# Generated by Django 1.9.5 on 2017-02-14 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0079_auto_20170213_2104'),
        ('dynadb', '0079_merge'),
        ('dynadb', '0078_auto_20170213_1850'),
    ]

    operations = [
    ]
