# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0079_auto_20170201_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbefficacy',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
