# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0080_auto_20170210_1643'),
        ('dynadb', '0082_auto_20170215_2017'),
    ]

    operations = [
    ]
