# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0083_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbreferences',
            name='url',
            field=models.URLField(blank=True, help_text='Uniform Resource Locator to the publication resource', max_length=250, null=True, verbose_name='URL'),
        ),
    ]
