# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0084_auto_20170216_1738'),
    ]

    operations = [
    ]
