# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0088_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcompound',
            name='iupac_name',
            field=models.TextField(),
        ),
    ]
