# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0089_auto_20170317_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbfilesdynamics',
            name='framenum',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
