# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0090_dyndbfilesdynamics_framenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyndbInhibition',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dynadb.DyndbExpInteractionData')),
                ('rvalue', models.FloatField()),
                ('units', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=900, null=True)),
            ],
            options={
                'db_table': 'dyndb_inhibition',
                'managed': True,
            },
        ),
    ]
