# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0091_dyndbinhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbefficacy',
            name='reference_id_efficacy',
            field=models.ForeignKey(db_column='reference_id_efficacy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbEfficacy'),
        ),
    ]
