# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-25 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0097_auto_20181125_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbsubmissiondynamicsfiles',
            name='files_dynamics_id',
            field=models.ForeignKey(blank=True, db_column='files_dynamics_id', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbFilesDynamics'),
        ),
    ]
