# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('dynadb', '0100_auto_20190226_1712'), ('dynadb', '0101_auto_20190226_1722'), ('dynadb', '0102_auto_20190226_1803'), ('dynadb', '0103_auto_20190226_2053')]

    dependencies = [
        ('dynadb', '0099_auto_20190129_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcomplexcompound',
            name='id_complex_exp',
            field=models.ForeignKey(db_column='id_complex_exp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dyndbcomplexcompoundcomplex', to='dynadb.DyndbComplexExp'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexcompound',
            name='id_compound',
            field=models.ForeignKey(db_column='id_compound', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dyndbcomplexcompoundcompound', to='dynadb.DyndbCompound'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexprotein',
            name='id_complex_exp',
            field=models.ForeignKey(db_column='id_complex_exp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dyndbcomplexproteincomplex', to='dynadb.DyndbComplexExp'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexprotein',
            name='id_protein',
            field=models.ForeignKey(db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dyndbcomplexproteinprotein', to='dynadb.DyndbProtein'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexcompound',
            name='id_complex_exp',
            field=models.ForeignKey(db_column='id_complex_exp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbComplexExp'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexcompound',
            name='id_compound',
            field=models.ForeignKey(db_column='id_compound', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbCompound'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexprotein',
            name='id_complex_exp',
            field=models.ForeignKey(db_column='id_complex_exp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbComplexExp'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexprotein',
            name='id_protein',
            field=models.ForeignKey(db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbProtein'),
        ),
        migrations.AddField(
            model_name='dyndbcomplexexp',
            name='compounds',
            field=models.ManyToManyField(through='dynadb.DyndbComplexCompound', to='dynadb.DyndbCompound'),
        ),
        migrations.AddField(
            model_name='dyndbcomplexexp',
            name='proteins',
            field=models.ManyToManyField(through='dynadb.DyndbComplexProtein', to='dynadb.DyndbProtein'),
        ),
        migrations.AddField(
            model_name='dyndbcomplexmolecule',
            name='molecules',
            field=models.ManyToManyField(through='dynadb.DyndbComplexMoleculeMolecule', to='dynadb.DyndbMolecule'),
        ),
    ]
