# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0099_auto_20190129_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcomplexcompound',
            name='id_complex_exp',
            field=models.ForeignKey(db_column='id_complex_exp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dyndbcomplexcompoundcomplex', to='dynadb.DyndbComplexExp'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexcompound',
            name='id_compound',
            field=models.ForeignKey(db_column='id_compound', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dyndbcomplexcompoundcompound', to='dynadb.DyndbCompound'),
        ),
    ]
