# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0103_auto_20200115_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbreferences',
            name='authors',
            field=models.CharField(blank=True, help_text='List of the authors separated by semicolon.', max_length=1000, null=True, verbose_name='Authors'),
        ),
    ]
