# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160719_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_new',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
