# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0006_auto_20160503_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbdynamics',
            options={'managed': True},
        ),
    ]
