# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0008_auto_20160509_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcompound',
            options={},
        ),
#       migrations.RemoveField(
#           model_name='dyndbsubmissionmodel',
#           name='model_id',
#       ),
    ]
