# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0009_auto_20160623_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcompound',
            options={'managed': False},
        ),
    ]
