# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('activation', models.BooleanField(default=False)),
            ],
        ),
    ]
