# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0003_auto_20160426_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='id_model',
            field=models.ForeignKey(db_column='id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_id_model_fky', to='dynadb.DyndbModel'),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, 'Ab-initio'), (1, 'Homology'), (2, 'Threading'), (3, 'Other Computational Methods')], default=0),
        ),
#       migrations.AlterField(
#           model_name='dyndbmodeledresidues',
#           name='template_id_model',
#           field=models.ForeignKey(blank=True, db_column='template_id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_template_id_protein_fky', to='dynadb.DyndbModel'),
#       ),
    ]
