# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0004_auto_20160426_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyndbSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dyndb_submission',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='DyndbDynamics',
            name='submission_id',
            field=models.ForeignKey('DyndbSubmission', models.DO_NOTHING, db_column='submission_id', blank=True, null=True ),   
        ),
        migrations.CreateModel(
            name='DyndbSubmissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.ForeignKey(blank=True, db_column='id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbModel')),
                ('submission_id', models.ForeignKey(blank=True, db_column='id_submission', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission')),
            ],
            options={
                'db_table': 'dyndb_submission_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DyndbSubmissionMolecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_in_model', models.BooleanField(null=True)),
                ('int_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('molecule_id', models.ForeignKey(blank=True, db_column='id_molecule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbMolecule')),
                ('submission_id', models.ForeignKey(blank=True, db_column='id_submission', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission')),
            ],
            options={
                'db_table': 'dyndb_submission_molecule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DyndbSubmissionProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('protein_id', models.ForeignKey(blank=True, db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbProtein')),
                ('submission_id', models.ForeignKey(blank=True, db_column='id_submission', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission')),
            ],
            options={
                'db_table': 'dyndb_submission_protein',
                'managed': True,
            },
        ),
    ]
