# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0012_auto_20160628_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcomplexcompound',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dyndbexpinteractiondata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dyndbexpproteindata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dyndbfilesdynamics',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dyndbfilesmolecule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dyndbmodel',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='dyndbdynamicscomponents',
            name='type',
            field=models.CharField(choices=[(0, 'Ions'), (1, 'Ligand'), (2, 'Membrane'), (3, 'Water'), (4, 'Other')], default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='dyndbmodelcomponents',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Ions'), (1, 'Ligand'), (2, 'Membrane'), (3, 'Water'), (4, 'Other')], default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, 'Ab-initio'), (1, 'Homology'), (2, 'Threading'), (3, 'Other Computational Methods'), (4, 'X-ray'), (5, 'NMR')], default=0),
        ),
    ]
