# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='act_code',
            field=models.CharField(default='test_code', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2016, 7, 19, 14, 42, 13, 277995, tzinfo=utc)),
        ),
    ]
