# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20160719_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2016, 7, 19, 15, 2, 35, 768703, tzinfo=utc)),
        ),
    ]
