# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160719_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2016, 7, 19, 15, 4, 0, 310700, tzinfo=utc)),
        ),
    ]
