# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20160719_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='act_code',
            field=models.CharField(default='PynaOYyiyK58n3qdokHqizujG1VDRUAbR', max_length=200),
        ),
    ]
