# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:41
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20160719_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='act_code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
