# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_email_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='act_code',
        ),
    ]
