# Generated by Django 4.1.5 on 2023-11-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('figname', models.TextField()),
                ('date', models.DateField()),
                ('figfile', models.TextField()),
                ('strucfile', models.TextField()),
            ],
            options={
                'db_table': 'figview',
            },
        ),
    ]
