# Generated by Django 4.1.5 on 2024-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='DOI')),
                ('authors', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Authors')),
                ('title', models.CharField(blank=True, max_length=900, null=True, verbose_name='Title')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('pmid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='PMID')),
                ('journal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Journal or Press')),
                ('pub_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Publication year')),
                ('issue', models.CharField(blank=True, max_length=10, null=True, verbose_name='Issue')),
                ('volume', models.CharField(blank=True, max_length=10, null=True, verbose_name='Volume')),
                ('pages', models.CharField(blank=True, max_length=16, null=True, verbose_name='Pages')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='URL')),
                ('url_image', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL image')),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
