# Generated by Django 4.1.5 on 2023-05-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_auto_20160926_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinPDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb', models.CharField(max_length=4, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.proteinstate')),
            ],
            options={
                'db_table': 'protein_pdb',
            },
        ),
    ]
