# Generated by Django 4.1.5 on 2023-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_proteinpdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinpdb',
            name='state',
            field=models.IntegerField(),
        ),
    ]
