# Generated by Django 4.1.5 on 2023-11-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0004_alter_proteinpdb_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinpdb',
            name='uniprotkbac',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
