# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynadb', '0104_auto_20200116_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDynamics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateField(default=django.utils.timezone.now)),
                ('author_name', models.CharField(max_length=200)),
                ('dyn_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'covid_dynamics',
            },
        ),
        migrations.CreateModel(
            name='CovidFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=80, unique=True)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('filepath', models.CharField(blank=True, max_length=520, null=True)),
                ('url', models.CharField(blank=True, max_length=520, null=True)),
                ('id_file_types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbFileTypes')),
            ],
            options={
                'db_table': 'covid_files',
            },
        ),
        migrations.CreateModel(
            name='CovidFilesDynamics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Input coordinates'), (1, 'Input topology'), (2, 'Trajectory'), (3, 'Parameters'), (4, 'Others')], default=0)),
                ('id_dynamics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='covid19.CovidDynamics')),
                ('id_files', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='covid19.CovidFiles')),
            ],
            options={
                'db_table': 'covid_files_dynamics',
            },
        ),
        migrations.AlterUniqueTogether(
            name='covidfilesdynamics',
            unique_together=set([('id_dynamics', 'id_files', 'type')]),
        ),
    ]
