# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Apoform (one single protein monomer)'), (1, 'Complex')], default=0)),
                ('pdbid', models.CharField(blank=True, max_length=6, null=True)),
                ('creation_timestamp', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'covid_model',
            },
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='id_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='covid19.CovidModel'),
        ),
    ]
