# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-18 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0004_coviddynamics_framenum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddynamics',
            name='framenum',
        ),
        migrations.AddField(
            model_name='covidfilesdynamics',
            name='framenum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
