# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0007_auto_20200914_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddynamics',
            name='atom_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='ff',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='ffversion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='software',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='sversion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='timestep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covidprotein',
            name='species',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='covidprotein',
            name='uniprot_entry',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
