# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0008_auto_20200921_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidprotein',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
