# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0009_auto_20200921_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddynamicscomponents',
            name='is_membrane',
            field=models.BooleanField(default=False),
        ),
    ]
