# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0012_auto_20201021_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddynamicscomponents',
            name='extracted_from_db',
        ),
        migrations.RemoveField(
            model_name='coviddynamicscomponents',
            name='extracted_from_db_entry',
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='extracted_from_db',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='extracted_from_db_entry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
