# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-21 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0013_auto_20201021_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddynamics',
            name='software',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
