# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-21 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0014_auto_20201021_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddynamics',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
