# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0015_auto_20201021_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frompos', models.IntegerField()),
                ('topos', models.IntegerField()),
                ('region_name', models.CharField(max_length=200)),
                ('uniprotkbac', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('evidence', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
