# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0016_coviddomains'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidModelSeqPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqpos', models.IntegerField()),
                ('aa', models.CharField(max_length=1)),
                ('chainid', models.CharField(blank=True, max_length=1, null=True)),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidFiles')),
            ],
        ),
        migrations.CreateModel(
            name='CovidSeqPositionsUniprotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modelpos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidModelSeqPositions')),
            ],
            options={
                'db_table': 'covid_seq_positions_uniprot_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CovidUniprotSeqPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqpos', models.IntegerField()),
                ('aa', models.CharField(max_length=1)),
                ('id_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidProtein')),
                ('models_position', models.ManyToManyField(blank=True, null=True, through='covid19.CovidSeqPositionsUniprotModel', to='covid19.CovidModelSeqPositions')),
            ],
            options={
                'db_table': 'covid_uniprot_seq_positions',
            },
        ),
        migrations.AddField(
            model_name='covidseqpositionsuniprotmodel',
            name='id_uniprotpos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidUniprotSeqPositions'),
        ),
        migrations.AlterUniqueTogether(
            name='coviduniprotseqpositions',
            unique_together=set([('id_protein', 'seqpos', 'aa')]),
        ),
        migrations.AlterUniqueTogether(
            name='covidseqpositionsuniprotmodel',
            unique_together=set([('id_uniprotpos', 'id_modelpos')]),
        ),
    ]
