# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0017_auto_20201104_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='covidseqpositionsuniprotmodel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='covidseqpositionsuniprotmodel',
            name='id_modelpos',
        ),
        migrations.RemoveField(
            model_name='covidseqpositionsuniprotmodel',
            name='id_uniprotpos',
        ),
        migrations.RemoveField(
            model_name='coviduniprotseqpositions',
            name='models_position',
        ),
        migrations.AddField(
            model_name='covidmodelseqpositions',
            name='id_uniprotpos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidUniprotSeqPositions'),
        ),
        migrations.DeleteModel(
            name='CovidSeqPositionsUniprotModel',
        ),
    ]
