# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0018_auto_20201104_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddomains',
            name='domain_seq',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
