# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-10 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0019_coviddomains_domain_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidModelProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': True,
                'db_table': 'covid_model_protein',
            },
        ),
        migrations.AlterField(
            model_name='covidmodel',
            name='id_protein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singleprot', to='covid19.CovidProtein'),
        ),
        migrations.AddField(
            model_name='covidmodelprotein',
            name='id_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidModel'),
        ),
        migrations.AddField(
            model_name='covidmodelprotein',
            name='id_protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidProtein'),
        ),
        migrations.AddField(
            model_name='covidmodel',
            name='proteins',
            field=models.ManyToManyField(null=True, through='covid19.CovidModelProtein', to='covid19.CovidProtein'),
        ),
        migrations.AlterUniqueTogether(
            name='covidmodelprotein',
            unique_together=set([('id_protein', 'id_model')]),
        ),
    ]
