# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-10 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0020_auto_20201110_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidmodel',
            name='id_protein',
        ),
    ]
