# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0021_remove_covidmodel_id_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidmodel',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'Experimental structure'), (1, 'Theoretical model')], default=0),
        ),
    ]
