# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0022_covidmodel_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidFinalProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CovidModelFinalProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_final_protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidFinalProtein')),
                ('id_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidModel')),
            ],
            options={
                'db_table': 'covid_model_finalprotein',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='covidmodel',
            name='final_proteins',
            field=models.ManyToManyField(null=True, through='covid19.CovidModelFinalProtein', to='covid19.CovidFinalProtein'),
        ),
        migrations.AlterUniqueTogether(
            name='covidmodelfinalprotein',
            unique_together=set([('id_final_protein', 'id_model')]),
        ),
    ]
