# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-11 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0023_auto_20201211_1250'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='covidmodelfinalprotein',
            table='covid_model_finalprotein',
        ),
    ]
