# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-14 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0025_auto_20201214_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidisolate',
            old_name='ymd',
            new_name='isolate_date',
        ),
    ]
