# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0026_auto_20201214_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidProteinFinalprotein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalprot_seq_start', models.IntegerField(blank=True, null=True)),
                ('finalprot_seq_end', models.IntegerField(blank=True, null=True)),
                ('id_finalprotein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidFinalProtein')),
                ('id_protein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.CovidProtein')),
            ],
            options={
                'db_table': 'covid_protein_finalprotein',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='covidprotein',
            name='final_proteins',
            field=models.ManyToManyField(null=True, through='covid19.CovidProteinFinalprotein', to='covid19.CovidFinalProtein'),
        ),
        migrations.AlterUniqueTogether(
            name='covidproteinfinalprotein',
            unique_together=set([('id_protein', 'id_finalprotein')]),
        ),
    ]
