# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0027_auto_20201217_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddynamics',
            name='is_shared_sc2md',
            field=models.BooleanField(default=False),
        ),
    ]
