# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0029_auto_20210423_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidmutations',
            name='mutfinc_data',
        ),
    ]
