# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0030_remove_covidmutations_mutfinc_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidmutfincdata',
            old_name='name',
            new_name='mutfunc_name',
        ),
        migrations.AddField(
            model_name='covidmutfincdata',
            name='id_final_protein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='covid19.CovidFinalProtein'),
        ),
    ]
