# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0032_auto_20210423_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidmutfincdata',
            old_name='ptmmodels',
            new_name='ptm',
        ),
    ]
