# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0033_auto_20210423_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidmutfincdata',
            name='annotation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
