# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0034_auto_20210423_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='covidmutfincdata',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='covidmutfincdata',
            name='id_final_protein',
        ),
        migrations.RemoveField(
            model_name='covidmutfincdatainterface',
            name='id_mutfunc_data',
        ),
        migrations.DeleteModel(
            name='CovidMutfincData',
        ),
        migrations.DeleteModel(
            name='CovidMutfincDataInterface',
        ),
    ]
