# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-23 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0035_auto_20210423_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidMutfuncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutfunc_name', models.CharField(blank=True, max_length=10, null=True)),
                ('uniprot', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.SmallIntegerField(blank=True, null=True)),
                ('wt', models.CharField(blank=True, max_length=1, null=True)),
                ('mut', models.CharField(blank=True, max_length=1, null=True)),
                ('freq', models.FloatField(blank=True, null=True)),
                ('ptm', models.CharField(blank=True, max_length=100, null=True)),
                ('sift_score', models.FloatField(blank=True, null=True)),
                ('sift_median', models.FloatField(blank=True, null=True)),
                ('template', models.CharField(blank=True, max_length=8, null=True)),
                ('relative_surface_accessibility', models.FloatField(blank=True, null=True)),
                ('foldx_ddg', models.FloatField(blank=True, null=True)),
                ('mut_escape_mean', models.FloatField(blank=True, null=True)),
                ('mut_escape_max', models.FloatField(blank=True, null=True)),
                ('annotation', models.CharField(blank=True, max_length=1000, null=True)),
                ('id_final_protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='covid19.CovidFinalProtein')),
            ],
        ),
        migrations.CreateModel(
            name='CovidMutfuncDataInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_uniprot', models.CharField(blank=True, max_length=10, null=True)),
                ('interaction_energy', models.FloatField(blank=True, null=True)),
                ('diff_interface_residues', models.FloatField(blank=True, null=True)),
                ('int_name', models.CharField(blank=True, max_length=10, null=True)),
                ('int_template', models.CharField(blank=True, max_length=8, null=True)),
                ('diff_interaction_energy', models.FloatField(blank=True, null=True)),
                ('id_mutfunc_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='covid19.CovidMutfuncData')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='covidmutfuncdata',
            unique_together=set([('mutfunc_name', 'position', 'mut')]),
        ),
    ]
