# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-05-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0037_auto_20210423_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidmutfuncdata',
            name='freqpermille',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
