# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-06-04 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0038_covidmutfuncdata_freqpermille'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidmodelseqpositions',
            name='ca_atom_index',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
