# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-07-03 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0039_covidmodelseqpositions_ca_atom_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidsequence',
            name='seq_idx_table',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
