# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-07-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0040_covidsequence_seq_idx_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidsequence',
            name='seq_idx_table',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covidsequencedgene',
            name='id_isolate',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='covid19.CovidIsolate', unique=True),
            preserve_default=False,
        ),
    ]
