# Generated by Django 4.1.5 on 2023-03-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0042_auto_20210703_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddynamics',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital object identifier.', max_length=80, null=True, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='solvent_is_filtered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coviddynamics',
            name='solvent_type',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Implicit'), (2, 'None'), (3, 'Other'), (4, 'TIP3P'), (5, 'TIP4P'), (6, 'TIPS'), (7, 'SPC'), (8, 'OPC')], default=0),
        ),
        migrations.AddField(
            model_name='coviddynamicscomponents',
            name='is_solvent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='covidmodel',
            name='final_proteins',
            field=models.ManyToManyField(through='covid19.CovidModelFinalProtein', to='covid19.covidfinalprotein'),
        ),
        migrations.AlterField(
            model_name='covidmodel',
            name='proteins',
            field=models.ManyToManyField(through='covid19.CovidModelProtein', to='covid19.covidprotein'),
        ),
        migrations.AlterField(
            model_name='covidprotein',
            name='final_proteins',
            field=models.ManyToManyField(through='covid19.CovidProteinFinalprotein', to='covid19.covidfinalprotein'),
        ),
        migrations.AlterField(
            model_name='covidsequence',
            name='seq_idx_table',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CovidSequenceMutatedPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.covidsequence')),
            ],
            options={
                'managed': True,
                'unique_together': {('id_mutated_pos', 'id_sequence')},
            },
        ),
    ]
