# Generated by Django 4.1.5 on 2023-05-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0043_coviddynamics_doi_coviddynamics_solvent_is_filtered_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CovidMutations',
            new_name='CovidMutatedPos',
        ),
        migrations.AddField(
            model_name='covidmutatedpos',
            name='id_final_protein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='covid19.covidfinalprotein'),
        ),
        migrations.AddField(
            model_name='covidsequence',
            name='seq_mutations',
            field=models.ManyToManyField(through='covid19.CovidSequenceMutatedPos', to='covid19.covidmutatedpos'),
        ),
        migrations.AddField(
            model_name='covidsequencemutatedpos',
            name='id_mutated_pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid19.covidmutatedpos'),
        ),
        migrations.AlterUniqueTogether(
            name='covidmutatedpos',
            unique_together={('resid', 'id_final_protein', 'resletter_from', 'resletter_to')},
        ),
        migrations.RemoveField(
            model_name='covidmutatedpos',
            name='id_sequence',
        ),
    ]
