# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Itype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residues', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyn_id', models.CharField(max_length=200)),
                ('receptor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='itype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='contact_maps.Itype'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='contact_maps.Positions'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='contact_maps.Simulation'),
        ),
    ]
