from django.urls import include, re_path
from rest_framework import routers

from . import views

# Routers
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    re_path(r'', include(router.urls)),
    re_path(r'^reference/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^protein/accession/(?P<accession>[^/].+)/$', views.ProteinByAccessionDetail.as_view(),
        name='proteinbyaccession'),
    re_path(r'^protein/(?P<entry_name>[^/].+)/$', views.ProteinDetail.as_view(), name='protein-detail'),
    re_path(r'^proteinfamily/$', views.ProteinFamilyList.as_view(), name='proteinfamily-list'),
    re_path(r'^proteinfamily/(?P<slug>[^/]+)/$', views.ProteinFamilyDetail.as_view(), name='proteinfamily-detail'),
    re_path(r'^proteinfamily/children/(?P<slug>[^/]+)/$', views.ProteinFamilyChildrenList.as_view(),
        name='proteinfamily-children'),
    re_path(r'^proteinfamily/descendants/(?P<slug>[^/]+)/$', views.ProteinFamilyDescendantList.as_view(),
        name='proteinfamily-descendants'),
    re_path(r'^proteinfamily/proteins/(?P<slug>[^/]+)/$', views.ProteinsInFamilyList.as_view(),
        name='proteinfamily-proteins'),
    re_path(r'^proteinfamily/proteins/(?P<slug>[^/]+)/(?P<latin_name>[^/]+)/$', views.ProteinsInFamilySpeciesList.as_view(),
        name='proteinfamily-proteins'),
    re_path(r'^residues/(?P<entry_name>[^/]+)/$', views.ResiduesList.as_view(), name='residues'),
    re_path(r'^residues/extended/(?P<entry_name>[^/]+)/$', views.ResiduesExtendedList.as_view(), name='residues-extended'),
    re_path(r'^alignment/family/(?P<slug>[^/]+)/$', views.FamilyAlignment.as_view(), name='familyalignment'),
    re_path(r'^alignment/family/(?P<slug>[^/]+)/statistics/$', views.FamilyAlignment.as_view(), {'statistics': True}, name='familyalignment-statistics'),
    re_path(r'^alignment/family/(?P<slug>[^/]+)/(?P<segments>[^/]+)/$', views.FamilyAlignmentPartial.as_view(),
        name='familyalignment-partial'),
    re_path(r'^alignment/family/(?P<slug>[^/]+)/(?P<segments>[^/]+)/statistics/$', views.FamilyAlignmentPartial.as_view(), {'statistics': True},
        name='familyalignment-partial-statistics'),
    re_path(r'^alignment/family/(?P<slug>[^/]+)/(?P<segments>[^/]+)/(?P<latin_name>[^/]+)/$', views.FamilyAlignmentPartialSpecies.as_view(),
        name='familyalignment-partial-statistics'),
    re_path(r'^alignment/family/(?P<slug>[^/]+)/(?P<segments>[^/]+)/(?P<latin_name>[^/]+)/statistics/$', views.FamilyAlignmentPartialSpecies.as_view(), {'statistics': True},
        name='familyalignment-partial'),
    re_path(r'^alignment/protein/(?P<proteins>[^/]+)/$', views.ProteinAlignment.as_view(),
        name='proteinalignment'),
    re_path(r'^alignment/protein/(?P<proteins>[^/]+)/statistics/$', views.ProteinAlignmentStatistics.as_view(), {'statistics': True},
        name='proteinalignment-statistics'),
    re_path(r'^alignment/protein/(?P<proteins>[^/]+)/(?P<segments>[^/]+)/$', views.ProteinAlignmentPartial.as_view(),
        name='proteinalignment-partial'),
    re_path(r'^alignment/protein/(?P<proteins>[^/]+)/(?P<segments>[^/]+)/statistics/$', views.ProteinAlignmentStatistics.as_view(), {'statistics': True},
        name='proteinalignment-statistics'),
    re_path(r'^alignment/similarity/(?P<proteins>[^/]+)/(?P<segments>[^/]+)/$', views.ProteinSimilaritySearchAlignment.as_view(),
        name='proteinsimilarityalignment'),
    re_path(r'^structure/$', views.StructureList.as_view(), name='structure-list'),
    re_path(r'^structure/representative/$', views.RepresentativeStructureList.as_view(), {'representative': True},
        name='structure-representative-list'),
    re_path(r'^structure/protein/(?P<entry_name>[^/]+)/$', views.StructureListProtein.as_view(),
        name='structure-list-protein'),
    re_path(r'^structure/protein/(?P<entry_name>[^/]+)/representative/$',
        views.RepresentativeStructureListProtein.as_view(), {'representative': True},
        name='representative-structure-list-protein'),
    re_path(r'^structure/(?P<pdb_code>[^/]+)/$', views.StructureDetail.as_view(), name='structure-detail'),
    re_path(r'^structure/(?P<pdb_code>[^/]+)/interaction/$', views.StructureLigandInteractions.as_view(), name='interaction'),
    re_path(r'^structure/template/(?P<entry_name>[^/]+)/$', views.StructureTemplate.as_view(),
        name='structuretemplate'),
    re_path(r'^structure/template/(?P<entry_name>[^/]+)/(?P<segments>[^/]+)/$', views.StructureTemplatePartial.as_view(),
        name='structuretemplate-partial'),
    re_path(r'structure/assign_generic_numbers$', views.StructureAssignGenericNumbers.as_view(),
        name='assign_generic_numbers'),
    re_path(r'structure/parse_pdb$', views.StructureSequenceParser.as_view(), name='sequence_parser'),
    re_path(r'^species/$', views.SpeciesList.as_view(), name='species-list'),
    re_path(r'^species/(?P<latin_name>[^/]+)/$', views.SpeciesDetail.as_view(), name='species-detail'),
    re_path(r'^mutants/(?P<entry_name>[^/].+)/$', views.MutantList.as_view(), name='mutants'),
    re_path(r'^drugs/(?P<entry_name>[^/].+)/$', views.DrugList.as_view(), name='drugs'),
    re_path(r'^plot/snake/(?P<entry_name>[^/].+)/$', views.SnakePlotView.as_view(), name='snakeplot'),
    re_path(r'^plot/helixbox/(?P<entry_name>[^/].+)/$', views.HelixBoxView.as_view(), name='helixbox')
]