# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juanmaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIPROTid', models.CharField(max_length=20)),
                ('iso', models.CharField(max_length=100)),
                ('MUT', models.CharField(max_length=4)),
                ('Nam', models.CharField(max_length=30)),
                ('ORGAN', models.CharField(max_length=200)),
                ('DescMOL', models.TextField()),
                ('NETc', models.IntegerField()),
                ('INCHI', models.TextField()),
                ('inchik', models.CharField(max_length=27)),
                ('SMI', models.TextField()),
                ('resnamMOL', models.CharField(max_length=5)),
                ('numMOL', models.IntegerField()),
                ('MAINprot', models.TextField()),
                ('MAINlig', models.TextField()),
                ('IONresn', models.CharField(max_length=5)),
                ('IONnum', models.IntegerField()),
                ('COMtyp', models.CharField(max_length=50)),
                ('idproT', models.CharField(max_length=50)),
                ('idcoM', models.CharField(max_length=50)),
                ('Msour', models.CharField(max_length=50)),
                ('PDB', models.CharField(max_length=4)),
                ('desc', models.TextField()),
                ('mTEMP', models.TextField()),
                ('METH', models.CharField(max_length=50)),
                ('SOFT', models.CharField(max_length=50)),
                ('SOFTver', models.CharField(max_length=50)),
                ('ffield', models.CharField(max_length=50)),
                ('MEMB', models.CharField(max_length=50)),
                ('Solv', models.CharField(max_length=50)),
                ('PDBcoor', models.CharField(max_length=50)),
                ('PSF', models.CharField(max_length=50)),
                ('topPSF', models.CharField(max_length=50)),
                ('par', models.CharField(max_length=50)),
                ('DCD', models.CharField(max_length=50)),
            ],
        ),
    ]
