# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juanmaapp', '0002_formup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyndbAssayTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60)),
            ],
            options={
                'managed': False,
                'db_table': 'dyndb_assay_types',
            },
        ),
    ]
