# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0005_dyndbsubmission_dyndbsubmissionmodel_dyndbsubmissionmolecule_dyndbsubmissionprotein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbsubmissionprotein',
            name='submission_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'), #Coge como columna de referencia por defecto a la PK de la tabla correspondiente 
        ),
    ]
