# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0011_auto_20160628_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyndbreferences',
            name='institution',
        ),
        migrations.AddField(
            model_name='dyndbdynamicscomponents',
            name='id_dynamics',
            field=models.ForeignKey(blank=True, db_column='id_dynamics', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbDynamics'),
        ),
        migrations.AddField(
            model_name='dyndbdynamicscomponents',
            name='id_molecule',
            field=models.ForeignKey(blank=True, db_column='id_molecule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbMolecule'),
        ),
        migrations.AddField(
            model_name='dyndbmodelcomponents',
            name='id_model',
            field=models.ForeignKey(blank=True, db_column='id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbModel'),
        ),
        migrations.AddField(
            model_name='dyndbmodelcomponents',
            name='id_molecule',
            field=models.ForeignKey(blank=True, db_column='id_molecule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbMolecule'),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='template_id_model',
            field=models.ForeignKey(blank=True, db_column='template_id_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_template_id_protein_fky', to='dynadb.DyndbModel'),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbdynamicscomponents',
            unique_together=set([('id_dynamics', 'id_molecule')]),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbmodelcomponents',
            unique_together=set([('id_model', 'id_molecule')]),
        ),
    ]
