# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0014_auto_20160630_2021'),
    ]

    operations = [
#       migrations.AddField(
#           model_name='dyndbefficacy',
#           name='id_functional',
#           field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbFunctional'),
#       ),
#       migrations.AddField(
#           model_name='dyndbefficacy',
#           name='reference_id_compound',
#           field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbCompound'),
#       ),
        migrations.AlterField(
            model_name='dyndbcomplexcompound',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Orthosteric ligand'), (1, 'Allosteric ligand'), (2, 'Crystallographic waters'), (3, 'Other')], default=0),
        ),
#       migrations.AlterField(
#           model_name='dyndbefficacy',
#           name='type',
#           field=models.SmallIntegerField(choices=[(0, 'Full Agonist'), (1, 'Partial Agonist'), (2, 'Antagonist'), (3, 'Inverse Agonist'), (4, 'Other')], default=0),
#       ),
        migrations.AlterField(
            model_name='dyndbexpinteractiondata',
            name='protein1',
            field=models.ForeignKey(db_column='protein1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbExpInteractionData_protein1_fky', to='dynadb.DyndbProtein'),
        ),
        migrations.AlterField(
            model_name='dyndbexpinteractiondata',
            name='protein2',
            field=models.ForeignKey(blank=True, db_column='protein2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbExpInteractionData_protein2_fky', to='dynadb.DyndbProtein'),
        ),
        migrations.AlterField(
            model_name='dyndbfilesdynamics',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Input coordinates'), (1, 'input topology'), (2, 'trajectory'), (3, 'others')], default=0),
        ),
#       migrations.AlterField(
#           model_name='dyndbfilesmolecule',
#           name='type',
#           field=models.SmallIntegerField(choices=[(0, 'Image'), (1, 'Molecule')], default=0),
#       ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='id_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_id_model_fky', to='dynadb.DyndbModel'),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='template_id_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_template_id_protein_fky', to='dynadb.DyndbModel'),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmolecule',
            name='molecule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbMolecule'),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmolecule',
            name='submission_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
        ),
#       migrations.AlterUniqueTogether(
#           name='dyndbfilesmolecule',
#           unique_together=set([('id_molecule', 'id_files')]),
#       ),
    ]
