# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0015_auto_20160705_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbefficacy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dyndbfilesmolecule',
            options={'managed': False},
        ),
    ]
