# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0023_auto_20160725_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbreferences',
            name='authors',
            field=models.CharField(blank=True, help_text='List of the authors separated by semicolon.', max_length=60, null=True, verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital object identifier.', max_length=80, null=True, unique=False, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='issue',
            field=models.CharField(blank=True, help_text='Issue number.', max_length=10, null=True, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='journal_press',
            field=models.CharField(blank=True, help_text='Name of the Journal or Press in case of a book.', max_length=60, null=True, verbose_name='Journal or Press'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='pages',
            field=models.CharField(blank=True, help_text='Initial and final pages of the publication separated by dash.', max_length=16, null=True, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='pmid',
            field=models.IntegerField(blank=True, help_text='PubMed identifier or PubMed unique identifier', null=True, unique=True, verbose_name='PMID'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='pub_year',
            field=models.SmallIntegerField(blank=True, help_text='Year of publication', null=True, verbose_name='Publication year'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the paper.', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='url',
            field=models.CharField(blank=True, help_text='Uniform Resource Locator to the publication resource', max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='dyndbreferences',
            name='volume',
            field=models.CharField(blank=True, help_text='Volume number.', max_length=10, null=True, verbose_name='Volume'),
        ),
    ]
