# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0024_auto_20160726_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcomplexprotein',
            options={'managed': True},
        ),
    ]
