# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0025_auto_20160817_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbprotein',
            options={'managed': True},
        ),
    ]
