# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0030_auto_20160911_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyndbcomplexmoleculemolecule',
            name='number',
        ),
        migrations.RemoveField(
            model_name='dyndbcomplexmoleculemolecule',
            name='resname',
        ),
    ]
