# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0032_auto_20160911_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbfiletypes',
            name='is_accepted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbfiletypes',
            unique_together=set([('type_name', 'extension')]),
        ),
    ]
