# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0039_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyndbmodeledresidues',
            name='bound_to_id_modeled_residues',
        ),
        migrations.AddField(
            model_name='dyndbmodeledresidues',
            name='bonded_to_id_modeled_residues',
            field=models.ForeignKey(db_column='bond_to_id_modeled_residues', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DyndbModeledResidues_bond_to_id_modeled_residues_fky', to='dynadb.DyndbModeledResidues'),
        ),
    ]
