# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0042_auto_20161004_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcompound',
            name='std_id_molecule',
            field=models.ForeignKey(blank=True, db_column='std_id_molecule', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbMolecule'),
        ),
        migrations.AlterField(
            model_name='dyndbmolecule',
            name='inchikey',
            field=models.CharField(db_index=True, default=1, max_length=27),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dyndbcompound',
            name='sinchikey',
            field=models.CharField(db_index=True, default=1, max_length=27),
            preserve_default=False,
        ),
    ]
