# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0043_auto_20161005_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcompound',
            name='sinchikey',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='dyndbmolecule',
            name='inchikey',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
