# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0052_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbmodel',
            name='name',
            field=models.TextField(default='unnamed model', max_length=100),
            preserve_default=False,
        ),
    ]
