# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0053_dyndbmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbsubmissionmodel',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='dyndbsubmissionmolecule',
            unique_together=set([('submission_id', 'int_id'), ('submission_id', 'molecule_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbsubmissionprotein',
            unique_together=set([('submission_id', 'int_id'), ('submission_id', 'protein_id')]),
        ),
    ]
