# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0054_auto_20161031_1541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dyndbsubmissionmodel',
            unique_together=set([('submission_id', 'model_id')]),
        ),
    ]
