# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0055_auto_20161031_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbdynamicscomponents',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Ions'), (1, 'Membrane'), (2, 'Water'), (3, 'Other')], default=0),
        ),
    ]
