# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0060_dyndbfiles_url'),
        ('dynadb', '0061_auto_20161207_1557'),
    ]

    operations = [
    ]
