# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0062_auto_20161222_2213'),
        ('dynadb', '0067_auto_20161230_1553'),
    ]

    operations = [
    ]
