# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0068_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbsubmissionmodel',
            name='submission_id',
            field=models.OneToOneField(blank=True, db_column='submission_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbsubmissionmodel',
            unique_together=set([]),
        ),
    ]
