# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0068_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcomplexexp',
            options={'managed': True},
        ),
    ]
