# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0071_auto_20170111_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbdynamics',
            name='atom_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
