# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-20 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0072_dyndbdynamics_atom_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dyndbdynamicscomponents',
            unique_together=set([('id_dynamics', 'id_molecule', 'resname')]),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbmodelcomponents',
            unique_together=set([('id_model', 'id_molecule', 'resname')]),
        ),
    ]
