# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0074_auto_20170120_1037'),
        ('dynadb', '0075_auto_20170124_1439'),
    ]

    operations = [
    ]
