# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0078_auto_20170213_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dyndbsubmissiondynamicsfiles',
            unique_together=set([('submission_id', 'filepath'), ('submission_id', 'type', 'filenum')]),
        ),
    ]
