# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0081_auto_20170215_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbfilesmodel',
            name='id_files',
            field=models.OneToOneField(db_column='id_files', on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbFiles'),
        ),
        migrations.AlterField(
            model_name='dyndbfilesmodel',
            name='id_model',
            field=models.OneToOneField(db_column='id_model', on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbModel'),
        ),
        migrations.AlterUniqueTogether(
            name='dyndbfilesmodel',
            unique_together=set([]),
        ),
    ]
