# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0083_auto_20170216_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyndbcomplexexp',
            options={'managed': True},
        ),
    ]
