# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-28 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0086_auto_20170224_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcompound',
            name='id_ligand',
            field=models.ForeignKey(blank=True, db_column='id_ligand', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ligand.Ligand'),
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='id_structure_model',
            field=models.ForeignKey(blank=True, db_column='id_structure_model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure.StructureModel'),
        ),
        migrations.AlterField(
            model_name='dyndbprotein',
            name='receptor_id_protein',
            field=models.ForeignKey(blank=True, db_column='receptor_id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='protein.Protein'),
        ),
    ]
