# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-02 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0087_auto_20170228_1952'),
        ('dynadb', '0086_auto_20170223_2116'),
    ]

    operations = [
    ]
