# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-09 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0092_dyndbefficacy_reference_id_efficacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbdynamics',
            name='id_model',
            field=models.ForeignKey(blank=True, db_column='id_model', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dyndbdynamics',
            name='submission_id',
            field=models.OneToOneField(blank=True, db_column='submission_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmodel',
            name='model_id',
            field=models.ForeignKey(blank=True, db_column='model_id', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dyndbsubmissionmodel',
            name='submission_id',
            field=models.OneToOneField(blank=True, db_column='submission_id', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbSubmission'),
            preserve_default=False,
        ),
    ]
