# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0100_auto_20190226_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcomplexprotein',
            name='id_complex_exp',
            field=models.ForeignKey(db_column='id_complex_exp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dyndbcomplexproteincomplex', to='dynadb.DyndbComplexExp'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexprotein',
            name='id_protein',
            field=models.ForeignKey(db_column='id_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dyndbcomplexproteinprotein', to='dynadb.DyndbProtein'),
        ),
    ]
