# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-07 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0100_auto_20190226_1712_squashed_0103_auto_20190226_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbcomplexexp',
            name='compounds',
            field=models.ManyToManyField(through='dynadb.DyndbComplexCompound', to='dynadb.DyndbCompound'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexexp',
            name='proteins',
            field=models.ManyToManyField(through='dynadb.DyndbComplexProtein', to='dynadb.DyndbProtein'),
        ),
        migrations.AlterField(
            model_name='dyndbcomplexmolecule',
            name='molecules',
            field=models.ManyToManyField(through='dynadb.DyndbComplexMoleculeMolecule', to='dynadb.DyndbMolecule'),
        ),
    ]
