# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-15 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0101_auto_20190307_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbdynamics',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
