# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-26 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0102_auto_20190226_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbcomplexexp',
            name='compounds',
            field=models.ManyToManyField(through='dynadb.DyndbComplexCompound', to='dynadb.DyndbCompound'),
        ),
        migrations.AddField(
            model_name='dyndbcomplexexp',
            name='proteins',
            field=models.ManyToManyField(through='dynadb.DyndbComplexProtein', to='dynadb.DyndbProtein'),
        ),
        migrations.AddField(
            model_name='dyndbcomplexmolecule',
            name='molecules',
            field=models.ManyToManyField(through='dynadb.DyndbComplexMoleculeMolecule', to='dynadb.DyndbMolecule'),
        ),
    ]
