# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0104_auto_20200116_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyndbFilesNonGPCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Input coordinates'), (1, 'model coordinates'), (2, 'Input topology'), (3, 'Trajectory'), (4, 'Parameters'), (5, 'Small molecule'), (6, 'Report'), (7, 'Others')], default=0)),
                ('filename', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DyndbNonGPCRDynamics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyn_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, 'X-ray'), (1, 'NMR'), (2, 'Docking'), (3, 'MD'), (5, 'Other'), (4, 'Electron microscopy')], default=0),
        ),
        migrations.AlterField(
            model_name='dyndbmodeledresidues',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, 'X-ray'), (1, 'NMR'), (2, 'Ab-initio'), (3, 'Homology'), (4, 'Threading'), (5, 'MD'), (6, 'Other Computational Methods'), (7, 'Electron microscopy')], default=0),
        ),
        migrations.AddField(
            model_name='dyndbfilesnongpcr',
            name='id_ngpcr_dynamics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynadb.DyndbNonGPCRDynamics'),
        ),
    ]
