# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-02 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0105_auto_20201202_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbfilesnongpcr',
            name='filepath',
            field=models.CharField(blank=True, max_length=520, null=True),
        ),
        migrations.AddField(
            model_name='dyndbfilesnongpcr',
            name='url',
            field=models.CharField(blank=True, max_length=520, null=True),
        ),
        migrations.AlterField(
            model_name='dyndbfilesnongpcr',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Input coordinates'), (1, 'Model coordinates'), (2, 'Input topology'), (3, 'Trajectory'), (4, 'Parameters'), (5, 'Small molecule'), (6, 'Report'), (7, 'Others')], default=0),
        ),
    ]
