# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0106_auto_20201202_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbfilesnongpcr',
            name='filename',
            field=models.CharField(max_length=80),
        ),
    ]
