# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0108_auto_20201202_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyndbNonGPCRLigand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resname', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=400)),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='dyndbfilesnongpcr',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dyndbnongpcrdynamics',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='accum_sim_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='assay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='atom_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='ff',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='ffversion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='is_mutant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='membrane',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='model_type',
            field=models.SmallIntegerField(choices=[(0, 'Apoform (one single protein monomer)'), (1, 'Complex')], default=0),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='pdbid',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='prot_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='software',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='solvent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='species_scientific_name',
            field=models.TextField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='sversion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='timestep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='uniprotkbac',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='up_entry_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='id_nongpcr_ligand',
            field=models.ForeignKey(blank=True, db_column='id_nongpcr_ligand', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynadb.DyndbNonGPCRLigand'),
        ),
    ]
