# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-03 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0109_auto_20201203_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbnongpcrdynamics',
            name='id_nongpcr_ligand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynadb.DyndbNonGPCRLigand'),
        ),
    ]
