# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0111_auto_20201204_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyndbfilesnongpcr',
            name='author_institution',
        ),
        migrations.RemoveField(
            model_name='dyndbfilesnongpcr',
            name='author_name',
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='author_institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dyndbnongpcrdynamics',
            name='author_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
