# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-04-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0112_auto_20201204_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbmodel',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, 'X-ray'), (1, 'NMR'), (2, 'Docking'), (3, 'MD'), (4, 'Electron microscopy'), (5, 'Other')], default=0),
        ),
    ]
