# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-04-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0113_auto_20220420_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbsubmission',
            name='is_gpcrmd_community',
            field=models.BooleanField(default=False),
        ),
    ]
