# Generated by Django 4.1.5 on 2023-03-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0115_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyndbbinding',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dynadb.dyndbexpinteractiondata'),
        ),
        migrations.AlterField(
            model_name='dyndbefficacy',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dynadb.dyndbexpinteractiondata'),
        ),
        migrations.AlterField(
            model_name='dyndbinhibition',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dynadb.dyndbexpinteractiondata'),
        ),
        migrations.AlterField(
            model_name='dyndbrelateddynamics',
            name='id_dynamics',
            field=models.OneToOneField(db_column='id_dynamics', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dynadb.dyndbdynamics'),
        ),
    ]
