# Generated by Django 4.1.5 on 2024-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0117_alter_dyndbfilesdynamics_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbprotein',
            name='prot_type',
            field=models.SmallIntegerField(choices=[(1, 'GPCR'), (2, 'G protein subunit'), (3, 'Beta arrestin'), (4, 'Peptide ligand'), (0, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, 'X-ray'), (1, 'NMR'), (2, 'Docking'), (3, 'MD'), (4, 'Electron microscopy (CryoEM)'), (5, 'Other')], default=0),
        ),
    ]
