# Generated by Django 4.1.5 on 2025-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0119_alter_dyndbmodel_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbmodel',
            name='state_type',
            field=models.SmallIntegerField(choices=[(0, ''), (1, 'Active'), (2, 'Intermidiate'), (3, 'Inactive')], default=0),
        ),
    ]
