# Generated by Django 4.1.5 on 2025-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynadb', '0120_dyndbmodel_state_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndbreferences',
            name='pub_code',
            field=models.CharField(blank=True, help_text='Publication code to identify unpublish submission that are together.', max_length=16, null=True, verbose_name='GPCRmd publication code'),
        ),
        migrations.AlterField(
            model_name='dyndbmodel',
            name='state_type',
            field=models.SmallIntegerField(choices=[(0, 'Unespecified'), (1, 'Active'), (2, 'Intermediate'), (3, 'Inactive')], default=0),
        ),
    ]
