-- DROP TABLE dev_public.auth_group CASCADE;  
-- DROP TABLE dev_public.auth_group_permissions CASCADE; 
-- DROP TABLE dev_public.auth_permission CASCADE; 
DROP TABLE dev_public.auth_user CASCADE; 
DROP TABLE dev_public.auth_user_groups CASCADE; 
DROP TABLE dev_public.auth_user_user_permissions CASCADE; 
DROP TABLE dev_public.construct_chemical CASCADE;  
DROP TABLE dev_public.construct_chemical_conc CASCADE; 
DROP TABLE dev_public.construct_chemical_list CASCADE; 
DROP TABLE dev_public.construct_chemical_list_chemicals CASCADE; 
DROP TABLE dev_public.construct_chemical_list_name CASCADE; 
DROP TABLE dev_public.construct_chemical_type CASCADE; 
DROP TABLE dev_public.construct_construct CASCADE;  
DROP TABLE dev_public.construct_construct_deletions CASCADE; 
DROP TABLE dev_public.construct_construct_insertions CASCADE; 
DROP TABLE dev_public.construct_construct_modifications CASCADE; 
DROP TABLE dev_public.construct_construct_mutations CASCADE; 
DROP TABLE dev_public.construct_contributorinfo CASCADE; 
DROP TABLE dev_public.construct_crystalinfo CASCADE;  
DROP TABLE dev_public.construct_crystallization CASCADE; 
DROP TABLE dev_public.construct_crystallization_chemical_lists CASCADE; 
DROP TABLE dev_public.construct_crystallization_ligand_conc CASCADE; 
DROP TABLE dev_public.construct_crystallization_ligands CASCADE; 
DROP TABLE dev_public.construct_crystallization_methods CASCADE; 
DROP TABLE dev_public.construct_crystallization_types CASCADE; 
DROP TABLE dev_public.construct_deletion CASCADE; 
DROP TABLE dev_public.construct_expression_system CASCADE; 
DROP TABLE dev_public.construct_insertion CASCADE; 
DROP TABLE dev_public.construct_insertion_type CASCADE; 
DROP TABLE dev_public.construct_modification CASCADE; 
DROP TABLE dev_public.construct_mutation CASCADE; 
DROP TABLE dev_public.construct_purification CASCADE; 
DROP TABLE dev_public.construct_purification_step CASCADE; 
DROP TABLE dev_public.construct_purification_steps CASCADE; 
DROP TABLE dev_public.construct_solubilization CASCADE; 
DROP TABLE dev_public.contact_maps_interaction CASCADE;  
DROP TABLE dev_public.contact_maps_itype CASCADE;  
DROP TABLE dev_public.contact_maps_positions CASCADE;  
DROP TABLE dev_public.contact_maps_simulation CASCADE;  
DROP TABLE dev_public.contact_plots_interaction CASCADE;  
DROP TABLE dev_public.contact_plots_itype CASCADE;  
DROP TABLE dev_public.contact_plots_positions CASCADE;  
DROP TABLE dev_public.contact_plots_simulation CASCADE;
-- DROP TABLE dev_public.covid19_coviddomains CASCADE;
-- DROP TABLE dev_public.covid19_covidfinalprotein CASCADE;
-- DROP TABLE dev_public.covid19_covidisolate CASCADE;
-- DROP TABLE dev_public.covid19_covidmodelseqpositions CASCADE;
-- DROP TABLE dev_public.covid19_covidmutatedpos CASCADE;
-- DROP TABLE dev_public.covid19_covidmutations CASCADE;
-- DROP TABLE dev_public.covid19_covidmutfuncdata CASCADE;
-- DROP TABLE dev_public.covid19_covidmutfuncdatainterface CASCADE;
-- DROP TABLE dev_public.covid19_covidsequence CASCADE;
-- DROP TABLE dev_public.covid19_covidsequencedgene CASCADE;
-- DROP TABLE dev_public.covid19_covidsequencemutatedpos CASCADE;
-- DROP TABLE dev_public.django_admin_log CASCADE;
-- DROP TABLE dev_public.django_content_type CASCADE;
-- DROP TABLE dev_public.django_migrations CASCADE;
-- DROP TABLE dev_public.django_session CASCADE;