# Generated by Django 4.1.5 on 2023-05-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alldownloads_dyn_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldownloads',
            name='last_update_by',
        ),
        migrations.RemoveField(
            model_name='alldownloads',
            name='last_update_by_dbengine',
        ),
        migrations.RemoveField(
            model_name='alldownloads',
            name='url',
        ),
    ]
