# Generated by Django 4.1.5 on 2023-05-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_alldownloads_last_update_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldownloads',
            name='id_file_types',
        ),
    ]
