# Generated by Django 4.1.5 on 2023-05-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_alldownloads_id_file_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldownloads',
            name='created_by',
        ),
    ]
