# Generated by Django 4.1.5 on 2023-05-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_alldownloads_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldownloads',
            name='dyn_ids',
            field=models.CharField(max_length=1000),
        ),
    ]
