# Generated by Django 4.1.5 on 2023-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_alldownloads_dyn_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldownloads',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
